import { describe, it, expect } from 'vitest';
import type { NarrativeResponse, NarrativeError } from '$lib/server/ai/types';

describe('AINarrativeBlock', () => {
	it('can be imported as a module', async () => {
		const mod = await import('./AINarrativeBlock.svelte');
		expect(mod.default).toBeDefined();
	});

	it('NarrativeResponse type enforces required fields', () => {
		const validResponse: NarrativeResponse = {
			summary: 'This patent demonstrates strong technological importance.',
			archetype: 'Specialist',
			generatedAt: new Date().toISOString()
		};

		expect(validResponse.summary).toBeTruthy();
		expect(validResponse.archetype).toBe('Specialist');
		expect(validResponse.generatedAt).toBeTruthy();
	});

	it('NarrativeResponse allows null archetype', () => {
		const response: NarrativeResponse = {
			summary: 'This patent has a balanced quality profile.',
			archetype: null,
			generatedAt: new Date().toISOString()
		};

		expect(response.archetype).toBeNull();
	});

	it('component accepts null narrative (self-hides pattern)', () => {
		// Type-level validation: null is a valid prop value
		const nullNarrative: NarrativeResponse | null = null;
		expect(nullNarrative).toBeNull();
	});

	it('all four archetype values are valid', () => {
		const archetypes = ['Specialist', 'Generalist', 'Disruptor', 'Incremental'] as const;

		for (const archetype of archetypes) {
			const response: NarrativeResponse = {
				summary: `Test summary for ${archetype}.`,
				archetype,
				generatedAt: new Date().toISOString()
			};
			expect(response.archetype).toBe(archetype);
		}
	});

	it('component template includes aria-live="polite" for accessibility', async () => {
		const fs = await import('fs');
		const path = await import('path');
		const componentPath = path.resolve(
			new URL('.', import.meta.url).pathname,
			'AINarrativeBlock.svelte'
		);
		const source = fs.readFileSync(componentPath, 'utf-8');

		expect(source).toContain('aria-live="polite"');
	});

	it('component template includes "Generated by Claude" attribution', async () => {
		const fs = await import('fs');
		const path = await import('path');
		const componentPath = path.resolve(
			new URL('.', import.meta.url).pathname,
			'AINarrativeBlock.svelte'
		);
		const source = fs.readFileSync(componentPath, 'utf-8');

		expect(source).toContain('Generated by Claude');
	});

	it('NarrativeError type has all expected error types', () => {
		const errorTypes: NarrativeError['type'][] = ['auth_error', 'no_key', 'api_error', 'timeout'];
		expect(errorTypes).toHaveLength(4);

		const authError: NarrativeError = { type: 'auth_error', message: 'Invalid key' };
		expect(authError.type).toBe('auth_error');

		const noKeyError: NarrativeError = { type: 'no_key', message: 'No key' };
		expect(noKeyError.type).toBe('no_key');
	});

	it('component template handles auth_error state', async () => {
		const fs = await import('fs');
		const path = await import('path');
		const componentPath = path.resolve(
			new URL('.', import.meta.url).pathname,
			'AINarrativeBlock.svelte'
		);
		const source = fs.readFileSync(componentPath, 'utf-8');

		expect(source).toContain('auth_error');
		expect(source).toContain('API key invalid or unauthorized');
	});

	it('component template handles no_key state with CTA', async () => {
		const fs = await import('fs');
		const path = await import('path');
		const componentPath = path.resolve(
			new URL('.', import.meta.url).pathname,
			'AINarrativeBlock.svelte'
		);
		const source = fs.readFileSync(componentPath, 'utf-8');

		expect(source).toContain('no_key');
		expect(source).toContain('Add your Anthropic API key in Settings');
		expect(source).toContain('onOpenSettings');
	});
});
