<script lang="ts">
	import type { NarrativeResponse } from '$lib/server/ai/types';
	import type { NarrativeError } from '$lib/scoring/types';
	import * as Card from '$lib/components/ui/card';
	import * as Collapsible from '$lib/components/ui/collapsible';
	import { Badge } from '$lib/components/ui/badge';
	import { Button } from '$lib/components/ui/button';
	import { ChevronDown, Settings, AlertTriangle } from '@lucide/svelte';
	import ProvenanceBadge from './ProvenanceBadge.svelte';

	interface Props {
		narrative: NarrativeResponse | null;
		narrativeError?: NarrativeError | null;
		onOpenSettings?: () => void;
	}

	let { narrative, narrativeError, onOpenSettings }: Props = $props();

	let isOpen = $state(false);

	function handleKeydown(event: KeyboardEvent) {
		if (event.key === 'Escape' && isOpen) {
			isOpen = false;
			event.stopPropagation();
		}
	}
</script>

{#if narrative}
	<div aria-live="polite">
		<Card.Root class="border-border border">
			<Card.Header>
				<Card.Title>AI Quality Summary</Card.Title>
			</Card.Header>
			<Card.Content>
				{#if narrative.archetype}
					<div class="mb-3 flex items-center gap-2">
						<Badge variant="secondary">{narrative.archetype}</Badge>
						<ProvenanceBadge
							provenance="PVE"
							title="Patent Archetypes are a Patent Value Explorer classification, not part of the OECD framework. See 'About patent archetypes' below for the rule set."
						/>
					</div>
				{/if}

				<p class="text-foreground text-base leading-relaxed" style="font-size: 16px;">
					{narrative.summary}
				</p>

				<!-- svelte-ignore a11y_no_static_element_interactions -->
				<div class="border-border mt-4 border-t" onkeydown={handleKeydown}>
					<Collapsible.Root bind:open={isOpen}>
						<Collapsible.Trigger
							class="text-muted-foreground hover:text-foreground flex w-full items-center gap-1.5 py-2 text-left text-xs font-medium transition-colors"
							aria-controls="archetype-info"
						>
							<ChevronDown
								class="h-3.5 w-3.5 shrink-0 transition-transform duration-200 {isOpen
									? 'rotate-180'
									: ''}"
							/>
							About patent archetypes
						</Collapsible.Trigger>
						<Collapsible.Content>
							<div id="archetype-info" class="space-y-2 pt-1 pb-3 text-xs">
								<p class="text-muted-foreground">
									The archetype is determined by the patent's average scores per dimension
									(Technological Importance, Market Relevance).
								</p>
								<dl class="grid gap-2">
									<div>
										<dt class="text-foreground font-medium">Specialist</dt>
										<dd class="text-muted-foreground">
											High scores in one dimension, moderate or low in others
										</dd>
									</div>
									<div>
										<dt class="text-foreground font-medium">Generalist</dt>
										<dd class="text-muted-foreground">
											Balanced scores across all dimensions (each above 0.5)
										</dd>
									</div>
									<div>
										<dt class="text-foreground font-medium">Disruptor</dt>
										<dd class="text-muted-foreground">
											High technological importance, low market relevance
										</dd>
									</div>
									<div>
										<dt class="text-foreground font-medium">Incremental</dt>
										<dd class="text-muted-foreground">
											Low scores across most dimensions (below 0.4 average)
										</dd>
									</div>
								</dl>
							</div>
						</Collapsible.Content>
					</Collapsible.Root>
				</div>

				<p class="text-muted-foreground mt-2 text-xs">Generated by Claude</p>
			</Card.Content>
		</Card.Root>
	</div>
{:else if narrativeError?.type === 'auth_error'}
	<Card.Root class="border-destructive/50 border">
		<Card.Content class="flex items-start gap-3 p-4">
			<AlertTriangle class="text-destructive mt-0.5 size-5 shrink-0" />
			<div>
				<p class="text-foreground text-sm font-medium">API key invalid or unauthorized</p>
				<p class="text-muted-foreground mt-1 text-xs">Check your key in Settings.</p>
			</div>
		</Card.Content>
	</Card.Root>
{:else if narrativeError?.type === 'no_key'}
	<Card.Root class="border-border border">
		<Card.Content class="flex items-start gap-3 p-4">
			<Settings class="text-muted-foreground mt-0.5 size-5 shrink-0" />
			<div>
				<p class="text-muted-foreground text-sm">
					Add your Anthropic API key in Settings to enable AI narratives.
				</p>
				{#if onOpenSettings}
					<Button variant="link" class="mt-1 h-auto p-0 text-xs" onclick={onOpenSettings}>
						Open Settings
					</Button>
				{/if}
			</div>
		</Card.Content>
	</Card.Root>
{:else if narrativeError}
	<Card.Root class="border-border border">
		<Card.Content class="flex items-start gap-3 p-4">
			<AlertTriangle class="text-muted-foreground mt-0.5 size-5 shrink-0" />
			<p class="text-muted-foreground text-sm">
				AI narrative generation failed. Try reloading the page.
			</p>
		</Card.Content>
	</Card.Root>
{/if}
